### ISSUE TITLE
Use custom redis config with RediSearch docker image?

### ISSUE THREAD

**Issue by ethanhann** [RedisLabsModules/RediSearch#144]
Am am not very familiar with docker. Is there an easy way to use a custom redis.conf file with the RediSearch docker image?

**Comment by ethanhann** [comment]
Apparently you can pass in arbitrary config options at the command line, like...

```
docker run -p 6379:6379 redislabs/redisearch:latest --requirepass foobar
```

That is sufficient for my needs.

**Comment by dvirsky** [comment]
@ethanhann this is based on the official redis image, where I think you can mount your config file somehow, it's actually better to allow this here as well. Let me see if I can do that

**Comment by MichelDiz** [comment]
Have you come to any point about this?
I am using this image for some studies. 
I wish I could edit her Config and add another module. See my yml

```yml
version: '3'
services:
  redis:
    container_name: redis_test
    hostname: redis
    image: redislabs/redisearch:latest
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf  #I was betting on this file location... none
    #even the commander get lost. It does not know how to find the config file. It's something else I'm             
    #going to look for a solution. For any new config location, the commander will not find it alone.

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: stevenaldinger/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8081:8081

```
