### ISSUE TITLE
redisearch forgets everything after restart

### ISSUE THREAD

**Issue by martinmakesitwork** [RedisLabsModules/RediSearch#241]
Hi erveryone. 

I try to run multiple redisearch instances inside docker. Everythings works well until i restart the whole thing. When i do docker-compose up and try to search inside an index. The redisearch container doesnt contain anything anymore. No indexes or data. How can i achieve it to save data properly?

This is my docker-compose file:
```yaml
version: '3.2'
services:
  app:
     ...
  rsearch1:
    image: redislabs/redisearch:latest
    container_name: rsearch1
    networks:
      - wordnet
    volumes:
      - redisearchdata1:/data
  rsearch2:
    image: redislabs/redisearch:latest
    container_name: rsearch2
    networks:
      - wordnet
    volumes:
      - redisearchdata2:/data
  rsearch3:
    image: redislabs/redisearch:latest
    container_name: rsearch3
    networks:
      - wordnet
    volumes:
      - redisearchdata3:/data
volumes:
  redisearchdata1:
    driver: "local"
  redisearchdata2:
    driver: "local"
  redisearchdata3:
    driver: "local"
networks:
  wordnet:
    driver: "bridge"
```

Thanks for every help.
